name: galleria_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  introduction_screen: ^3.1.17
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  
  # Firebase Dependencies (เวอร์ชันที่เข้ากันได้)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bunny_collector/bunny_collector_1.jpg
    - assets/images/bunny_collector/bunny_collector_2.jpg
    - assets/images/bunny_collector/bunny_collector_3.jpg
    - assets/images/pocket_zoo/pocket_zoo_1.jpg
    - assets/images/pocket_zoo/pocket_zoo_2.jpg
    - assets/images/pocket_zoo/pocket_zoo_3.jpg
    - assets/images/rua_rua_zoo/rua_rua_zoo1.jpg
    - assets/images/rua_rua_zoo/rua_rua_zoo2.jpg
    - assets/images/rua_rua_zoo/rua_rua_zoo3.jpg
    - assets/images/secret_forest/secret_forest_1.jpg
    - assets/images/secret_forest/secret_forest_2.jpg
    - assets/images/secret_forest/secret_forest_3.jpg
    - assets/images/tea_party/tea_party_1.jpg
    - assets/images/tea_party/tea_party_2.jpg
    - assets/images/tea_party/tea_party_3.jpg
    - assets/images/beloved/beloved_1.jpg
    - assets/images/beloved/beloved_2.jpg
    - assets/images/beloved/beloved_3.jpg
    - assets/images/avatar/avatar1.png
    - assets/images/avatar/avatar2.png
    - assets/images/avatar/avatar3.png
    - assets/images/avatar/profile.png
    - assets/images/dream_rosegarden/dream_rosegarden_1.jpg
    - assets/images/dream_rosegarden/dream_rosegarden_2.jpg
    - assets/images/dream_rosegarden/dream_rosegarden_3.jpg
    - assets/images/witch_feast/witch_feast_1.jpg
    - assets/images/witch_feast/witch_feast_2.jpg
    - assets/images/witch_feast/witch_feast_3.jpg
    - assets/images/intropic/post3.jpeg
    - assets/images/intropic/post2.png
    - assets/images/intropic/post1.png