// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// 
/// void main() async {
///   await Firebase.initializeApp(
///     options: DefaultFirebaseOptions.currentPlatform,
///   );
/// }
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3WM2_8cvMrA5U37MLF0yDRR6gvjh65-g',
    appId: '1:715076972329:web:d57c0f847197a83aad9138',
    messagingSenderId: '715076972329',
    projectId: 'galleryapp-3375f',
    authDomain: 'galleryapp-3375f.firebaseapp.com',
    storageBucket: 'galleryapp-3375f.firebasestorage.app',
    measurementId: 'G-2Y4NQNTSTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXQ-HLaVwK0g_4R9tvKbHCr9hxCRNw2-Q',
    appId: '1:715076972329:android:1dcb17092b185531ad9138',
    messagingSenderId: '715076972329',
    projectId: 'galleryapp-3375f',
    storageBucket: 'galleryapp-3375f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1Yn4_t7V8qfCRRwehdHbugicNtxmzko',
    appId: '1:715076972329:ios:27fc80b9d17e8432ad9138',
    messagingSenderId: '715076972329',
    projectId: 'galleryapp-3375f',
    storageBucket: 'galleryapp-3375f.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1Yn4_t7V8qfCRRwehdHbugicNtxmzko',
    appId: '1:715076972329:ios:27fc80b9d17e8432ad9138',
    messagingSenderId: '715076972329',
    projectId: 'galleryapp-3375f',
    storageBucket: 'galleryapp-3375f.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3WM2_8cvMrA5U37MLF0yDRR6gvjh65-g',
    appId: '1:715076972329:web:352323279b19b54cad9138',
    messagingSenderId: '715076972329',
    projectId: 'galleryapp-3375f',
    authDomain: 'galleryapp-3375f.firebaseapp.com',
    storageBucket: 'galleryapp-3375f.firebasestorage.app',
    measurementId: 'G-5RRB49XN3S',
  );
}